### ISSUE TITLE
No New Zealand content

### ISSUE THREAD

**Issue by chabbly** [KathyReid/super-acme-software#6]
## Expected Behavior
Expect to see NZ content: e.g. Kiwi emoticon; Jandals; All Blacks; Jacinda

## Actual Behavior
No NZ content: only stupid AU content!

## Steps to Reproduce the Problem

1. Open the program.
2. Review home screen.
3. Look for NZ content.

## Specifications

  - Version: 3.2
  - Platform: MacOS

**Comment by chabbly** [comment]
Still waiting for NZ content. When can I expect a response on this??

**Comment by KathyReid** [comment]
Kia ora! Jacinda forever bruh! 

Unfortunately we are not planning to support NZ at this time, but if you would like to add Te Reo Maori translations you're more than welcome. 

Thanks again for your excellent suggestion.
