### ISSUE TITLE
What is a GitHub?

### ISSUE THREAD

**Issue by tomc3000** [KathyReid/super-acme-software#7]
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by KathyReid** [comment]
Thanks @tomc3000 for your question, and thanks for your interest in this project. 
You can learn more about GitHub at: 
https://lab.github.com/githubtraining/introduction-to-github

Hope you see you contributing to the Ace Super Software project soon! :tada:
